"""Clone and pin the two external reference repositories into `external/`.

`external/` is git-ignored (the clones are large and are not this project's
code); `configs/external_revisions.md` is the committed record of which
commit each machine should check out, regenerated by this module.
"""

from __future__ import annotations

import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

REPOS: dict[str, str] = {
    "Dr-CiK": "https://github.com/ServiceNow/Dr-CiK.git",
    "context-is-key-forecasting": "https://github.com/ServiceNow/context-is-key-forecasting.git",
}

# (path relative to the clone, symbol to look for) named by Decision D and U0.3.
VERIFY_TARGETS: dict[str, list[tuple[str, str]]] = {
    "context-is-key-forecasting": [
        ("cik_benchmark/baselines/direct_prompt.py", "def make_prompt"),
        ("cik_benchmark/metrics/crps.py", "def crps"),
        ("cik_benchmark/metrics/crps.py", "def crps_quantile"),
    ],
}

REVISIONS_RELATIVE_PATH = "configs/external_revisions.md"
_COMMIT_RE = re.compile(r"^## (?P<name>.+)\n(?:.*\n)*?- Commit: `(?P<commit>[0-9a-f]{7,40})`", re.MULTILINE)


def _run(cmd: list[str], cwd: Path | None = None) -> str:
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, check=True)
    return result.stdout.strip()


def read_pinned_commits(repo_root: Path) -> dict[str, str]:
    path = repo_root / REVISIONS_RELATIVE_PATH
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    return {m.group("name"): m.group("commit") for m in _COMMIT_RE.finditer(text)}


def clone_or_update(repo_root: Path, name: str, pinned_commit: str | None) -> str:
    """Clone if missing, else fetch. Checks out `pinned_commit` if given, else stays on HEAD."""
    url = REPOS[name]
    dest = repo_root / "external" / name
    if not dest.exists():
        _run(["git", "clone", url, str(dest)])
    else:
        _run(["git", "fetch", "origin"], cwd=dest)
    if pinned_commit:
        _run(["git", "checkout", pinned_commit], cwd=dest)
        return pinned_commit
    return _run(["git", "rev-parse", "HEAD"], cwd=dest)


def verify_targets(repo_root: Path, name: str) -> list[dict]:
    results = []
    for rel_path, symbol in VERIFY_TARGETS.get(name, []):
        p = repo_root / "external" / name / rel_path
        exists = p.exists()
        symbol_found = exists and symbol in p.read_text(encoding="utf-8", errors="ignore")
        results.append({"path": rel_path, "exists": exists, "symbol": symbol, "symbol_found": symbol_found})
    return results


def sync_all(repo_root: Path, machine_name: str) -> dict:
    pinned = read_pinned_commits(repo_root)
    summary: dict = {}
    for name in REPOS:
        commit = clone_or_update(repo_root, name, pinned.get(name))
        summary[name] = {"commit": commit, "verified": verify_targets(repo_root, name)}
    _write_revisions_md(repo_root, summary, machine_name)
    return summary


def _write_revisions_md(repo_root: Path, summary: dict, machine_name: str) -> None:
    now = datetime.now(timezone.utc).isoformat()
    lines = [
        "# External repository revisions",
        "",
        "Pinned commits for the reference repositories cloned into `external/` (git-ignored).",
        "Regenerated by `uv run utrack external sync`; the first sync on a machine pins",
        "whatever commit it clones, later syncs (on either machine) check that commit out.",
        "",
    ]
    for name, url in REPOS.items():
        info = summary[name]
        lines += [
            f"## {name}",
            f"- URL: {url}",
            f"- Commit: `{info['commit']}`",
            f"- Synced: {now} on {machine_name}",
            "",
        ]
        if info["verified"]:
            lines.append("Verified paths (Decision D, U0.3):")
            for check in info["verified"]:
                if check["symbol_found"]:
                    status = "OK"
                elif not check["exists"]:
                    status = "file missing"
                else:
                    status = "symbol not found"
                lines.append(f"- `{check['path']}` ({check['symbol']}): {status}")
            lines.append("")
    (repo_root / REVISIONS_RELATIVE_PATH).write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def doctor_status(repo_root: Path) -> dict[str, str]:
    pinned = read_pinned_commits(repo_root)
    status: dict[str, str] = {}
    for name in REPOS:
        dest = repo_root / "external" / name
        if not dest.exists():
            status[name] = "not cloned"
            continue
        try:
            head = _run(["git", "rev-parse", "HEAD"], cwd=dest)
        except subprocess.CalledProcessError:
            status[name] = "not a git repo"
            continue
        expected = pinned.get(name)
        if expected is None:
            status[name] = f"cloned at {head[:12]} (not yet pinned in {REVISIONS_RELATIVE_PATH})"
        elif head == expected:
            status[name] = f"OK ({head[:12]})"
        else:
            status[name] = f"MISMATCH local={head[:12]} pinned={expected[:12]}"
    return status
